services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - /home/foadm/data/postgres/18:/var/lib/postgresql/18/docker
    

